### ISSUE TITLE
Task list items are not aligned with their checkbox

### ISSUE THREAD

**Issue by arturolinares** [standardnotes/markdown-visual#11]
The checkbox is not aligned with the text in task lists.

OS: Linux (OpenSuse)
App: Desktop version (AppImage)
Theme: Default

![image](https://user-images.githubusercontent.com/203078/163088325-b369ce59-25dd-4bc6-b8bd-92f5817b865b.png)

I can see the checkbox is aligned in the milkdown demo site:

![image](https://user-images.githubusercontent.com/203078/163089048-b25c2d07-7e4a-4c0c-b88c-02ae7b0ce74b.png)

**Comment by johnny243** [comment]
Hey @arturolinares, thanks for reporting. The issue has been fixed in [v3.20.0](https://github.com/standardnotes/desktop/releases/tag/v3.20.0).
