### ISSUE TITLE
line spacing is too large ?

### ISSUE THREAD

**Issue by mrtpcet** [standardnotes/markdown-visual#2]
Wouldn't the line spacing be too large?
Thanks for your work !

**Comment by stefan-yas** [comment]
Screenshot?

**Comment by mrtpcet** [comment]
![Capture d’écran   2022-03-11 à 08 36 11](https://user-images.githubusercontent.com/60814449/157823117-1a81aa9f-7b68-4919-8060-a48645762812.png)

same on the desktop app

**Comment by johnny243** [comment]
Fixed via #8
