### ISSUE TITLE
Code Block Syntax Colors aren't derived from Theme

### ISSUE THREAD

**Issue by raygervais** [standardnotes/markdown-visual#7]
In themes like Solarized for example, the text becomes unreadable 

_solarized_

![image](https://user-images.githubusercontent.com/14265337/158207611-a7c6d364-0c3c-40a6-8999-d8ac396bcacf.png)

_focus_
![image](https://user-images.githubusercontent.com/14265337/158207773-45ee93b1-71ab-4ebe-8803-2994fccd018e.png)

_futura_
![image](https://user-images.githubusercontent.com/14265337/158207879-564c39b7-d499-49a5-8bc3-86da7c2e5cbe.png)

_midnight_
![image](https://user-images.githubusercontent.com/14265337/158207961-ff8ad0fa-f8ba-492c-bfe2-425ff47bbb21.png)

**Comment by johnny243** [comment]
Hi @raygervais, thanks for opening this issue!

What browser are you using? Or perhaps are you using the `desktop` app?

**Comment by raygervais** [comment]
This was the desktop app, on Fedora Linux.
Version of app: 3.13.0
